import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/Navbar/Navbar";
import { cn } from "@/lib/utils";
import Providers from "@/components/Providers/Providers";
import Header from "@/components/Header/page";
import Menu from "@/components/Menu/page";
import Footer from "@/components/Footer/page";
import { ProviderRedux } from "@/components/Redux/provider";
import MetaTags from "@/components/MetaTags";


// import ScrollToTopButton from "@/components/ScrollToTopButton/ScrollToTopButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VNU - Đại học Quốc gia Hà Nội",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProviderRedux>
        <MetaTags />
        <body className={cn('relative h-full font-sans antialiased')} suppressHydrationWarning={true}>
          <main className="relative flex flex-col min-h-screen">
            <Providers>
              <Header />
              <div className="flex-grow flex-1">
                {children}
                {/* <ScrollToTopButton/> */}
              </div>
              <Footer />
            </Providers>
          </main>
        </body>
      </ProviderRedux>
    </html>
  );
}
