// metadata.ts
import { Metadata } from 'next';

type MetadataOptions = {
  title?: string;
  description?: string;
};

export const createMetadata = ({ title = "Tri Nam", description = "Generated by create next app" }: MetadataOptions): Metadata => {
  return {
    title,
    description,
  };
};
